theme: jekyll-theme-hacker
title: YetiCodeCamp - C++ for Beginners
email: yeticodecamp@gmail.com
description: Companion website for the C++ for Beginners YouTube video series.
github_username: YetiCodeCamp
include: ['_pages', '_video_pages']
timezone: America/Chicago
